In [1]:
import numpy as np

In [2]:
state_values = np.zeros((5, 5))
gamma = 0.9
actions = np.array([[0,1], [0,-1], [1,0], [-1,0]])
print(actions)

In [5]:
def do(state, action):
    new_state = state + action
    reward = 0
    if np.array_equal(state, np.array([0,1])):
        reward = 10
        new_state = np.array([4,1])
    elif np.array_equal(state, np.array([0,3])):
        reward = 5
        new_state = np.array([2,3])  
    elif new_state.min() < 0 or new_state.max()>=5:
        reward = -1
        new_state = state
    return new_state, reward

In [5]:
def calc_val(state):
    action_prob = 1./len(actions)
    val = 0.
    for action in actions:
        new_state, reward = do(state, action)
        val += action_prob * (reward+gamma*state_values[new_state[0], new_state[1]])
    return val

# Enforcing uniform policy

In [6]:
for i in range(1000):
    for x in range(5):
        for y in range(5):
            for action in actions:
                state_values[x, y] = calc_val(np.array([x,y]))

In [7]:
print(state_values)

[[ 3.30899634  8.78929186  4.42761918  5.32236759  1.49217876]
 [ 1.52158807  2.99231786  2.25013995  1.9075717   0.54740271]
 [ 0.05082249  0.73817059  0.67311326  0.35818621 -0.40314114]
 [-0.9735923  -0.43549543 -0.35488227 -0.58560509 -1.18307508]
 [-1.85770055 -1.34523126 -1.22926726 -1.42291815 -1.97517905]]


In [1]:
import numpy as np

In [2]:
state_values = np.zeros((5, 5))
gamma = 0.9
actions = np.array([[0,1], [0,-1], [1,0], [-1,0]])
print(actions)

[[ 0  1]
 [ 0 -1]
 [ 1  0]
 [-1  0]]


In [7]:
def calc_val(state):
    vals = []
    for action in actions:
        new_state, reward = do(state, action)
        vals.append(reward+gamma*state_values[new_state[0], new_state[1]])
    return np.array(vals).max()

# Finding optimal greedy

In [8]:
for i in range(1000):
    for x in range(5):
        for y in range(5):
            for action in actions:
                state_values[x, y] = calc_val(np.array([x,y]))

In [9]:
print(state_values)

[[21.97748529 24.4194281  21.97748529 19.4194281  17.47748529]
 [19.77973676 21.97748529 19.77973676 17.80176308 16.02158677]
 [17.80176308 19.77973676 17.80176308 16.02158677 14.4194281 ]
 [16.02158677 17.80176308 16.02158677 14.4194281  12.97748529]
 [14.4194281  16.02158677 14.4194281  12.97748529 11.67973676]]
